# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e64bf5f23c1ef4ab300e8ef729b4eae25efb7e771e004a1c78de3a5d743de18555f5acba2a575b805d2514fbac925e31e2feb7bb997bfb7ca84607aac04e40fd

test:
  secret_key_base: ecf0566f30e9c2058d411c31d8fa10003bef82047ab50e0a5868359e63c9bfbedb9e4dc182e8994bb54332c89b0fb191a36be81ce8eb40c60d9db83c08d8a64c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
